### ISSUE TITLE
Website menu

### ISSUE THREAD

**Issue by haggis78** [haggis78/BreconChurch#11]
@amberpeddicord I was giving some further thought to the menu for the website. The headings I remember discussing yesterday afternoon included "about","sources", "history" and "maps". I think it would be great to add "timeline", "glossary", and "people". Although there are only four people mentioned in the document, we also know about some of the people who made and/or owned the copies we're looking at.

**Comment by amberpeddicord** [comment]
@haggis78 I'll try to fit them in! I'm attempting to do a dropdown menu at least for the "About" section, and was thinking of putting "history", "glossary", and a section with information about us. I figured it would help us condense things, but I'm still unsure about exactly how to organize things. Does that sound good for now, though?

**Comment by haggis78** [comment]
@amberpeddicord I guess you're right that it would be horizontally crowded. Maybe we will want a vertical menu column on the left instead of a banner menu? But we can rearrange things as we go along, and yes, that sounds find for now.

**Comment by ebeshero** [comment]
@haggis78 @amberpeddicord I tend to recommend against drop-down menus (even though they seem like a good way to organize a lot of headings). The issue is that they tend to be hard for users to control on different web browsers, and the drop-downs literally cover up portions of the main window. I like how @alnopa9 dealt with this on the Banksy project: she organized the main menu headings to always be just in one row across the top (no drop-down), and then as you click to enter each main menu page, you get the sub-headings: http://banksy.newtfire.org/index.html
Something similar is happening in the Toscana site (which is a little more like yours in serving up manuscript data): http://toscana.newtfire.org/  Here @zme1 actually just has a really simple menu bar across the top, and no drop-downs, but inside the pages you find lots of sub-pages listed.

The idea here is that the menu doesn't have to reach every single page you post on your site, but it can lead to main landing pages that can then contain subheadings. That might be easier to manage!

**Comment by amberpeddicord** [comment]
@ebeshero That sounds like a better plan. Thank you!
