### ISSUE TITLE
Collating with I

### ISSUE THREAD

**Issue by amberpeddicord** [haggis78/BreconChurch#13]
In manuscript I, every time Ricardus/Richardus is used, its abbreviated like this: 

<img width="88" alt="Screen Shot 2019-11-02 at 9 44 51 AM" src="https://user-images.githubusercontent.com/50875456/68071888-b1e2f780-fd55-11e9-9a40-1b0ee997cf01.png">

I'm unsure if this is an abbreviation, but I'm not sure which version (Ricardus or Richardus) it would be considered, or if it is its own version!

@haggis78

**Comment by haggis78** [comment]
Amber,

Excellent question! Yes, it's an abbreviation, but whether the scribe was thinking Richardus or Ricardus is not clear. For the moment, what about recording it as a separate option, coding it as Ric'us, and making a note to decide about it later?

Thanks,
Dr. Campbell

William H. Campbell, PhD, LMS, FRHistS
History Department
University of Pittsburgh-Greensburg
Faculty Office Building, Room 104
150 Finoli Drive
Greensburg, PA 15601

https://greensburg-pitt.academia.edu/CampbellW
________________________________

**Comment by amberpeddicord** [comment]
@haggis78 Sounds good! 

And one more question: were we coding when the manuscripts replaced æ with e? We may have talked about this, but I can't remember off the top of my head.

**Comment by haggis78** [comment]
Amber,

No, we weren't coding for ae/e in general, on the grounds that I thought all the later MSS used ae and only the old roll, R, used e. Are there places where we have ae in the xml file but MS I gives e? It my be hard to tell since sometimes the a in ae is reduced to a very tiny flattened loop on the lower left of the e. You could send me an image if you're not sure. But if it's unmistakably just an e, let's code for that.

Thanks for all of your hard work on this project.

-Dr. Campbell

William H. Campbell, PhD, LMS, FRHistS
History Department
University of Pittsburgh-Greensburg
Faculty Office Building, Room 104
150 Finoli Drive
Greensburg, PA 15601

https://greensburg-pitt.academia.edu/CampbellW
________________________________
