### ISSUE TITLE
Patent Roll Images

### ISSUE THREAD

**Issue by ChinoyIndustries** [haggis78/BreconChurch#23]
before I go through and create images for all of the <ab>'s I thought I should put the first few up and ask for some opinions. there's a new folder in site/images/ called patent-roll-images-web-size, with one set of images that are just the cut segments of the manuscript containing each <ab>, and one set where each <ab> is actually cut out and edited a bit (they're GIFs with transparency). These present much better, in my opinion, but they don't necessarily retain the feel of the manuscript as well. Any preferences?

**Comment by haggis78** [comment]
Good thinking. I like the edited versions -- are those just cut differently, or is there more to it?

Three thoughts:

1) Because the ab's are in flux in the xml document, it might be best to use letters rather than numbers in the file handles for the images. It would be easier to remember that, say, ab 10 in the text corresponds with image K than with image 11.

2) As we discussed before, line numbers down the left margin would be great. In fact, since the images are wide enough that users may need to scroll back and forth, it would be better still if they can be placed down _both_ margins. They can be superimposed over the image of the manuscript itself if you can find a text color that will show up well -- maybe a light red? You might need to re-cut some of these images so there is enough room in the margins. To make sure you don't get off track, which would be frustrating to fix, you can double-check it as you go against the old MS Word typescript I made of much of R; I numbered the lines in that.

3) There is a heading in the left margin at the top of the document. I want to include a transcription of that with the rest of R. Can you do a picture of that too, please? No line numbers needed.

Tally ho!

**Comment by ChinoyIndustries** [comment]
encountered some severe technical difficulties. posting completed images now.
