### ISSUE TITLE
Menu bar SSI issue on Comparison page

### ISSUE THREAD

**Issue by ebeshero** [haggis78/BreconChurch#25]
@alnopa9 @amberpeddicord Something's not working on the comparison page with the SSI: http://brecon.newtfire.org/html/comparison.html  and it seems like the menu links are outdated (pointing to Timeline.xhtml for example). I bet it's an easy fix, and maybe you're repairing it already, but I wanted to point it out because with everything else happening on the Brecon website just now it might be easy to overlook.

**Comment by alnopa9** [comment]
@ebeshero Checking it out now!

**Comment by alnopa9** [comment]
@ebeshero Fixed! I forgot to remove the navbar from the html after I was done working on it locally and I had to update the navbar because I did still have it linked to xhtml pages. @amberpeddicord server is ready to be updated.
[commit](https://github.com/haggis78/BreconChurch/commit/aa1d413efc13d472bdba394d95c48c975bcf5f3a)
